# Generated by Django 3.2.25 on 2025-07-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shuup_testing", "0006_djange2_updates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ultrafilter",
            options={},
        ),
    ]
