version: "3.7"

services:
  shuup:
    build:
      context: .
      dockerfile: Dockerfile.uv
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv  # Exclude virtual environment from volume mount
      - /app/.sqlite
      - /app/shuup/admin/static
      - /app/shuup/front/static
      - /app/shuup/gdpr/static
      - /app/shuup/notify/static
      - /app/shuup/regions/static
      - /app/shuup/themes/classic_gray/static
      - /app/shuup/xtheme/static
    environment:
      - DJANGO_SETTINGS_MODULE=shuup_workbench.settings.dev
    tty: true
    restart: unless-stopped
