[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shuup"
dynamic = ["version"]
description = "E-Commerce Platform"
authors = [
    {name = "Shuup Commerce Inc.", email = "shuup@shuup.com"}
]
license = {text = "OSL-3.0"}
readme = "README.rst"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

[project.urls]
Homepage = "http://shuup.com/"
Repository = "https://github.com/shuup/shuup"
Documentation = "https://shuup.readthedocs.io/"

[tool.setuptools.dynamic]
version = {attr = "shuup._version.__version__"}

[tool.black]
exclude = "migrations/.*|.eggs|.git|.tox|.venv|_build|buck-out|build|dist"
line_length = 120
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
known_django = "django"
known_first_party = "shuup"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip_glob = ["*/migrations/*", "*/venv/*", "*/.venv/*"]

[tool.flake8]
max-line-length = 120
ignore = ["E203", "W503", "E501"]
exclude = [
    "migrations",
    "venv",
    ".venv",
    ".git",
    ".tox",
    "dist",
    "doc",
    "*.egg",
    "build"
]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
follow_imports = "silent"
show_column_numbers = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
warn_redundant_casts = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "shuup_workbench.test_settings"
addopts = [
    "--tb=short",
    "--strict-markers",
    "--disable-warnings",
    "--cov=shuup",
    "--cov-report=html",
    "--cov-report=term-missing"
]
testpaths = ["shuup_tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "slow: marks tests as slow",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]

[tool.coverage.run]
source = ["shuup"]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/test_*.py",
    "*/.venv/*",
    "*/venv/*",
    "setup.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

[tool.pylint.main]
load-plugins = ["pylint_django"]
django-settings-module = "shuup_workbench.settings.dev"

[tool.pylint.messages_control]
disable = [
    "missing-docstring",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
    "too-many-locals",
    "too-many-branches",
    "duplicate-code",
]

[tool.pylint.format]
max-line-length = 120
