# UV configuration for Shuup project
# This file configures the UV package manager

# Python version requirement
requires-python = ">=3.8"

# Package index configuration
index-url = "https://pypi.org/simple"

# Extra index URLs (if needed)
# extra-index-url = []

# Package resolution strategy
resolution = "highest"

# Prerelease handling
prerelease = "disallow"

# Platform and environment settings
# python-platform = "linux"
# python-implementation = "cpython"

# Dependency resolution
# exclude-newer = "2024-01-01"

# Development tools configuration
[tool.uv]
dev-dependencies = [
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "pylint>=2.17.0",
    "mypy>=1.5.0",
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "pytest-django>=4.5.2",
    "pylint-django>=2.5.3",
    "django-debug-toolbar>=4.2.0",
    "django-extensions>=3.2.3",
    "pre-commit>=3.4.0",
]

# Workspace configuration
workspace = true
