# Generated by Django 3.2.25 on 2025-06-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_customer_group_pricing', '0001_squashed_0002_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgpdiscount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cgpprice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
