# Generated by Django 3.2.25 on 2025-07-01 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuup", "0100_auto_20250629_1956"),
    ]

    operations = [
        migrations.CreateModel(
            name="PiecesSalesUnit",
            fields=[
                (
                    "salesunit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shuup.salesunit",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
            bases=("shuup.salesunit",),
        ),
        migrations.CreateModel(
            name="SalesUnitAsDisplayUnit",
            fields=[
                (
                    "displayunit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shuup.displayunit",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
            bases=("shuup.displayunit",),
        ),
    ]
