# Generated by Django 3.2.25 on 2025-07-04 20:12

from django.db import migrations
import shuup.core.fields
import shuup.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("shuup", "0103_auto_20250704_0614"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesunitasdisplayunit",
            name="displayunit_ptr",
        ),
        migrations.AlterField(
            model_name="shopproduct",
            name="backorder_maximum",
            field=shuup.core.fields.QuantityField(
                blank=True,
                decimal_places=9,
                default=None,
                help_text="The number of units that can be purchased after the product is already sold out (out of stock). Set to blank for product to be purchasable without limits.",
                max_digits=36,
                null=True,
                validators=[shuup.core.validators.validate_nonzero_quantity],
                verbose_name="backorder maximum",
            ),
        ),
        migrations.DeleteModel(
            name="PiecesSalesUnit",
        ),
        migrations.DeleteModel(
            name="SalesUnitAsDisplayUnit",
        ),
    ]
