# Generated by Django 3.2.25 on 2025-07-04 21:37

from django.db import migrations
import django.db.models.deletion
import shuup.core.models._base


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("shuup", "0104_remove_managed_false_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="PiecesSalesUnit",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shuup.salesunit",),
        ),
        migrations.AlterField(
            model_name="contact",
            name="polymorphic_ctype",
            field=shuup.core.models._base.RecursionSafeForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_shuup.contact_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="servicebehaviorcomponent",
            name="polymorphic_ctype",
            field=shuup.core.models._base.RecursionSafeForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_shuup.servicebehaviorcomponent_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="polymorphic_ctype",
            field=shuup.core.models._base.RecursionSafeForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_shuup.serviceprovider_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
