# Generated by Django 3.2.25 on 2025-06-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_front', '0003_add_supplier_and_basket_class_spec_to_stored_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedbasket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
