# Generated by Django 3.2.25 on 2025-07-04 21:37

from django.db import migrations
import django.db.models.deletion
import shuup.core.models._base


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("campaigns", "0021_auto_20250629_1956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketdiscounteffect",
            name="polymorphic_ctype",
            field=shuup.core.models._base.RecursionSafeForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_campaigns.basketdiscounteffect_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="basketlineeffect",
            name="polymorphic_ctype",
            field=shuup.core.models._base.RecursionSafeForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_campaigns.basketlineeffect_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="productdiscounteffect",
            name="polymorphic_ctype",
            field=shuup.core.models._base.RecursionSafeForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_campaigns.productdiscounteffect_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
