

ORDER_REFERENCE_NUMBER_LENGTH_FIELD = "order_reference_number_length"
ORDER_REFERENCE_NUMBER_PREFIX_FIELD = "order_reference_number_prefix"
ORDER_REFERENCE_NUMBER_METHOD_FIELD = "order_reference_number_method"
