name: "PYPI"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release, e.g. 1.0.0"
        required: true

jobs:
  build:
    name: "Build and publish to PyPI"
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # For trusted publishing

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          ref: 'v${{ github.event.inputs.version }}'

      - name: "Install uv"
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: "Set up Python"
        run: uv python install 3.11

      - name: "Set up Node"
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: "Install gettext"
        run: sudo apt-get install --no-install-recommends --assume-yes gettext

      - name: "Install dependencies"
        run: uv sync --dev

      - name: "Build static resources"
        run: uv run python setup.py build_resources

      - name: "Compile messages"
        run: cd shuup && uv run shuup_workbench compilemessages

      - name: "Build the package"
        run: |
          rm -rf build/
          rm -rf dist/
          uv build

      - name: "Verify the build"
        run: |
          uv run twine check dist/*
          ls -la dist/

      - name: "Upload to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
