name: CI

on:
  push:
    branches: [ master, 3.x ]
  pull_request:
    branches: [ master, 3.x ]

jobs:

  codestyle:
    name: "Code style & sanity checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    - name: Set up Python
      run: uv python install 3.11
    - name: Sync dependencies
      run: uv sync --dev
    - name: Check ruff lint
      run: uv run ruff check .
    - name: Check ruff format
      run: uv run ruff format --check --diff .

  core:
    name: "Test Shuup, migrations and messages"
    runs-on: ubuntu-latest
    env:
      SHUUP_BROWSER_TESTS: 0
      SHUUP_TESTS_CI: 1
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}
    - name: Create virtual environment
      run: uv venv .venv
    - name: Install build dependencies
      run: uv add setuptools wheel --dev
    - name: Install gettext
      run: sudo apt-get -y install gettext
    - name: Install system dependencies
      run: sudo apt-get -y install libffi-dev
    - name: Install dependencies (without editable)
      run: uv sync --dev
    - name: Install package in editable mode
      run: uv pip install -e .
    - name: Create logs folder
      run: mkdir .unit_tests
    - name: Validate Selenium WebDriver fixes
      run: uv run shuup_workbench test_selenium_fixes
    - name: Run makemessages
      run: cd shuup && uv run shuup_workbench shuup_makemessages -l en
    - name: Run tests
      run: uv run pytest --nomigrations shuup_tests --cov shuup --cov-config=.coveragerc
    - name: Run compilemessages
      run: uv run shuup_workbench compilemessages --ignore=**/site-packages/**
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: unit_tests
        path: .unit_tests/*.*

  browser:
    name: "Test Shuup with browser"
    runs-on: ubuntu-latest
    env:
      SHUUP_BROWSER_TESTS: 1
      SHUUP_TESTS_CI: 1
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}

    - name: "Setup Firefox driver"
      uses: browser-actions/setup-geckodriver@latest
    - run: geckodriver --version

    - name: Install gettext
      run: sudo apt-get -y install gettext

    - name: Install system dependencies
      run: sudo apt-get -y install libffi-dev

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Create virtual environment
      run: uv venv .venv

    - name: Install dependencies (without editable)
      run: uv sync --dev

    - name: Install package in editable mode
      run: uv pip install -e .

    - name: Build static files
      run: uv run shuup-build-resources

    - name: Compile messages
      run: uv run python shuup_workbench compilemessages --ignore=**/site-packages/**

    - name: Create logs folder
      run: mkdir .unit_tests

    - name: Validate Selenium WebDriver fixes
      run: uv run shuup_workbench test_selenium_fixes

    - name: Run tests
      run: uv run pytest -v --nomigrations shuup_tests/browser/front shuup_tests/browser/admin --splinter-headless --splinter-screenshot-dir=.unit_tests/

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: unit_tests
        path: .unit_tests/*.*
